name: fah-build-main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ "linux", "darwin", "windows" ]
        arch: ["amd64", "arm64"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: go build -o fah-exporter-${{ matrix.os }}-${{ matrix.arch }} -v ./...

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fah-exporter-${{ matrix.os }}-${{ matrix.arch }}
          path: fah-exporter-${{ matrix.os }}-${{ matrix.arch }}